steps:

  - name: ":package: Package Plugin"
    artifact_paths: target/scala-2.12/*
    command: sbt package

  - name: ":cloud: Publish to S3"
    command: >
     buildkite-agent artifact download target/scala-2.12/harana-idea-plugin*.jar . &&
     aws s3 cp target/scala-2.12/harana-idea-plugin*.jar s3://deploy-buildkite-packages/harana-idea-plugin
